### ISSUE TITLE
Breaks Brinstar's My Music

### ISSUE THREAD

**Issue by Roadhog360** [libertyernie/BrawlManagers#11]
Any time I have this code active, no matter what, Brinstar doesn't work. Softlocks on load.
Its My Music appears as Menu's and soflocks the stage on load.
If I try to use any tracklist modifiers to fix it, it will not work.

**Comment by libertyernie** [comment]
On the first tab, try putting another stage (like a second Battlefield or
something) in the spot where Brinstar is now. Then just don't use that new
stage anywhere on the 2nd or 3rd tabs. I don't have my regular computer
with me at the moment but I kind of remember having to do this for
something.

**Comment by Roadhog360** [comment]
So in the stage/icon pair tab? Also, how do I contact you better, I've been trying for weeks but couldn't find anything but this.
I see you are in Smashboards but it's been over a year since your last login there.

**Comment by Roadhog360** [comment]
Hey, it worked! But if you made the code, you should still fix this, I spend almost a week trying to.

**Comment by libertyernie** [comment]
I didn't make the code, I actually don't really know how it works.

I log on to kc:mm sometimes, but this so probably the best way to get in
touch with me.

On Jun 23, 2017 4:55 PM, "Roadhog360" <notifications@github.com> wrote:

Hey, it worked! But if you made the code, you should still fix this, I
spend almost a week trying to.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/libertyernie/BrawlManagers/issues/11#issuecomment-310781711>,
or mute the thread

**Comment by fancythedeveloper** [comment]
This also happens to Mushroomy Kingdom.

**Comment by Roadhog360** [comment]
Not for me.
Maybe you applied the fix incorrectly.

**Comment by Roadhog360** [comment]
This issue should be closed.
